Add files via upload

diff --git a/ffmpeg_full_ocheb b/ffmpeg_full_ocheb
--- a/ffmpeg_full_ocheb
+++ b/ffmpeg_full_ocheb
@@ -14,7 +14,7 @@ Final license of rezulted package is complex and nonfree.
         
 Build process is not fully automatic, your presence is required (for a sudo privileges)
 "
-sleep 50
+sleep 15
 
 who=$(whoami)
 if [ "$who" == "root" ]; then echo "
@@ -65,9 +65,9 @@ exit 1
 fi
 
 ## extra optimizations off
-cat get_ffmpeg-full_arch | sed 's/sudo pacman/yes | sudo pacman/g' | sed 's/#echo /echo /g' >get_ffmpeg-full_arch.
+#cat get_ffmpeg-full_arch | sed 's/sudo pacman/yes | sudo pacman/g' | sed 's/#echo /echo /g' >get_ffmpeg-full_arch.
 ## extra optimizations on
-#cat get_ffmpeg-full_arch | sed 's/sudo pacman/yes | sudo pacman/g' >get_ffmpeg-full_arch.
+cat get_ffmpeg-full_arch | sed 's/sudo pacman/yes | sudo pacman/g' >get_ffmpeg-full_arch.
 
 chown $who get_ffmpeg-full_arch.
 chmod +x get_ffmpeg-full_arch.
@@ -96,14 +96,15 @@ sudo umount processdir/dev
 sudo umount processdir/sys
 sudo umount processdir
 
-if $(cat upper/build/build.log | grep -x --regexp="failed retrieving file" | grep -q --regexp="error: "); then
-echo "
-It seems something goes wrong... Build fail
-Check upper/build/build.log
-"
-exit 1
-fi
+# if $(cat upper/build/build.log | grep -v --regexp="failed retrieving file" | grep -iq --regexp="error: "); then
+# echo "
+# It seems something goes wrong... Build fail
+# Check upper/build/build.log
+# "
+# exit 1
+# fi
 
+cp -f upper/build/build.log build.log
 echo clear build
 sudo rm -fr processdir work upper/build upper/tmp upper/root upper/var upper/home upper/etc/sudoers
 echo search and remove character files
@@ -112,6 +113,9 @@ for ii in $(find upper/ ! -type d); do
 done
 
 tar -czvf source.tar.gz upper
+
+## remove upper dir
+sudo rm -fr upper
 
 ## set final pkg params, change it as you want
 pkgname=ffmpeg-full-ocheb
@@ -163,8 +167,13 @@ install -m755 $prefix''$j $pkgdir/usr/bin/$prefix''$j
 EOf
 
 makepkg
+
+rm -fr pkg src
+
 if (ls | grep -q pkg.tar.xz); then
 echo "
+because buildfail detection gives false positive result, it was turned off
+
 the package is
 '$(ls | grep pkg.tar.xz)'
                                             do not forget to install it
